# Please update dev-requirements accordingly when updating black and ruff versions.
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos
        args: ["--write-changes", "--force-exclude"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ["--write"]
        types: [file]
        files: \.(md|html|css)$
